# Generated by Django 3.0.5 on 2020-04-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='is_pc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='character',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
